/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Advise {
    public String getFish() {
        return "When in doubt, fish!";
    }

    public static void main(String[] args) {
        System.out.println(new Advise().getFish());
    }
}
