# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  message_1:
    docker:
      - image: circleci/openjdk:latest
    steps:
      # Replace this with a real test runner invocation
      - run:
          name: hello world
          command: |
          echo 'public class Main { public static void main(String[] args) { System.out.println("There\'s no such thing as a bad day when you\'re fishing"); } }' > App1.java
      - run:
          name: Compile Java Program
          command: javac App1.java
      - run:
          name: Run Java Program
          command: java App1

  message_2:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - run:
          name: hello world
          command: |
          echo 'public class Main { public static void main(String[] args) { System.out.println(\"When in doubt, fish!\"); } }' > App2.java
      - run:
          name: Compile Java Program
          command: javac App2.java
      - run:
          name: Run Java Program
          command: java App2

workflows:
  version: 2
  print_messages:
    jobs:
      - message_1
      - message_2
