version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_TAG: docker/scout-demo-service:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - run:
          name: Install Docker Scout
          command: |
            curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /home/circleci/bin
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_HUB_PAT | docker login -u $DOCKER_HUB_USER --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_TAG .
      - run:
          name: Scan image for CVEs
          command: docker-scout cves $IMAGE_TAG --exit-code --only-severity critical,high

workflows:
  version: 2
  build-docker-image:
    jobs:
      - build
