# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  message_1:
    docker:
      - image: cimg/openjdk:15.0
      - image: aquasec/trivy:latest
    steps:
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Scan Docker Image
          command: docker run --rm -e GITHUB_TOKEN=$GITHUB_TOKEN -v trivy-cache:/root/.cache/ -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image cimg/openjdk:15.0

      - run:
          name: Docker Login
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      # Replace this with a real test runner invocation
      - run:
          name: Do Code
          command: |
            echo 'public class App1 { public static void main(String[] args) { System.out.println("There'\''s no such thing as a bad day when you'\''re fishing"); } }' > App1.java
      - run:
          name: Compile Java Program
          command: javac App1.java
      - run:
          name: Run Java Program
          command: java App1

  message_2:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Docker Login
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - run:
          name: Do Code
          command: |
            echo 'public class App2 { public static void main(String[] args) { System.out.println("When in doubt, fish!"); } }' > App2.java
      - run:
          name: Compile Java Program
          command: javac App2.java
      - run:
          name: Run Java Program
          command: java App2

workflows:
  version: 2.1
  print_messages:
    jobs:
      - message_1
      - message_2